spring:
  application:
    name: ai-shop

  datasource:
    url: jdbc:postgresql://localhost:5432/devdb
    username: devuser
    password: devpass
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  kafka:
    topic:
      rollback: rollback
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

logging:
  level:
    org.springframework.web: DEBUG

JWT_SECRET: super-secret-key-super-secret-key
